package com.example.plantdiseasephenotype.utils;

public class ModelClassesLinks {
    public static String[] MODEL_CLASSES_Links = new String[]{
            "https://plantdiseasephenotype.blogspot.com/2020/07/apple-scab.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/apple-black-rot.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/apple-cedar-rust.html",
            "",
            "",
            "",
            "https://plantdiseasephenotype.blogspot.com/2020/11/cherry-powdery-mildrew.html",
            "",
            "https://plantdiseasephenotype.blogspot.com/2020/11/corn-gray-leaf-spot.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/corn-common-rust.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/corn-northern-leaf-blight.html",
            "",
            "https://plantdiseasephenotype.blogspot.com/2020/11/grape-black-rot.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/grape-black-measles.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/grape-leaf-blight.html",
            "",
            "https://plantdiseasephenotype.blogspot.com/2020/11/orange-huanglongbing.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/peach-bacterial-spot.html",
            "",
            "https://plantdiseasephenotype.blogspot.com/2020/11/bell-pepper-bacterial-spot.html",
            "",
            "https://plantdiseasephenotype.blogspot.com/2020/11/potato-early-blight.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/potato-late-blight.html",
            "",
            "",
            "",
            "https://plantdiseasephenotype.blogspot.com/2020/11/squash-powdery-mildew.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/strawberry-leaf-scorch.html",
            "",
            "https://plantdiseasephenotype.blogspot.com/2020/11/tomato-bacterial-spot.html",
            "https://plantdiseasephenotype.blogspot.com/2020/07/early-blight.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/tomato-late-blight.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/tomato-leaf-mold.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/tomato-septoria-leaf-spot.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/tomato-two-spotted-spider-mite.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/tomato-target-spot.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/tomato-mosaic-virus.html",
            "https://plantdiseasephenotype.blogspot.com/2020/11/tomato-yellow-leaf-curl-virus.html",
            ""
    };
}
