package com.example.plantdiseasephenotype.utils;

public class ModelClasses {
    public static String[] MODEL_CLASSES = new String[]{
            "Apple Scab",
            "Apple Black Rot",
            "Apple Cedar Rust",
            "Apple Healthy",
            "Blueberry Healthy",
            "Cherry Powdery Mildew",
            "Cherry Healthy",
            "Corn Gray Leaf Spot",
            "Corn Common Rust",
            "Corn Northern Leaf Blight",
            "Corn Healthy",
            "Grape Black Rot",
            "Grape Black Measles",
            "Grape Leaf Blight",
            "Grape Healthy",
            "Orange Huanglongbing",
            "Peach Bacterial Spot",
            "Peach Healthy",
            "Bell Pepper Bacterial Spot",
            "Bell Pepper Healthy",
            "Potato Early Blight",
            "Potato Late Blight",
            "Potato Healthy",
            "Raspberry Healthy",
            "Soybean Healthy",
            "Squash Powdery Mildew",
            "Strawberry Leaf Scorch",
            "Strawberry Healthy",
            "Tomato Bacterial Spot",
            "Tomato Early Blight",
            "Tomato Late Blight",
            "Tomato Leaf Mold",
            "Tomato Septoria Leaf Spot",
            "Tomato Two Spotted Spider Mite",
            "Tomato Target Spot",
            "Tomato Yellow Leaf Curl Virus",
            "Tomato Mosaic Virus",
            "Tomato Healthy"
    };
}
